### ISSUE TITLE
Log Trafic validation throw a null reference exception

### ISSUE THREAD

**Issue by lucianareginalino** [ava-innersource/Liquid-Application-Framework-1.0-deprecated#18]
If developer not load NLog in service locator,  Result() method (hilighted below) throw a null reference exception.

https://github.com/Avanade/Liquid-Application-Framework/blob/d625dff6d3af90fc9aba210f8898564b7b4f02c7/src/Liquid.Activation/Controller/LightController.cs#L72

**Comment by bruno-brant** [comment]
As already explored in issues #29 and #30, `ILightLogger` is currently mandatory, but I agree that some people might just use `ILightTelemetry.TrackTrace`. Therefore, we should create a feature flag so that `ILightLogger` becomes optional and the code @lucianareginalino mentioned above doesn't throw.
